### ISSUE TITLE
3.1.2 only works 

### ISSUE THREAD

**Issue by antsav** [1000ch/atom-cssfmt#17]
tried latest 2 versions (3.2.1 and 3.2.0) and it's not working for me. 
only version 3.1.2 works fine 
my .stylelintrc is as simple as : 

```
{
    "extends": "stylelint-config-standard",
    "rules": {
        "indentation": 4,
        "number-leading-zero": null,
        "declaration-empty-line-before": "never",
        "comment-empty-line-before": null,
        "unit-whitelist": [
            "px",
            "em",
            "rem",
            "s",
            "%",
            "deg",
            "ms"
        ]
    }
}
```

**Comment by gucong3000** [comment]
Please try this PR #16

**Comment by gucong3000** [comment]
`stylefmt` has API change, `atom-stylefmt` need to update. see: https://github.com/1000ch/atom-stylefmt/pull/16/files

**Comment by antsav** [comment]
can u please just merge so we'll just update from apm ?

**Comment by gucong3000** [comment]
> can u please just merge so we'll just update from apm ?
@1000ch
