### ISSUE TITLE
Your gif is broken!

### ISSUE THREAD

**Issue by axe312ger** [1000ch/atom-cssfmt#6]
Hey there, was happy to see a demonstration.. but suddenly.. after the context menu appears, the gif gets white in Chrome. My Atom editor just restarts it at the point where Chrome turns white.

Redo it, i can really recomment http://www.cockos.com/licecap/ for stress free gif capturing on OSX

Have a nice day and thx for your work,
Ben

**Comment by 1000ch** [comment]
Fixed 👌

**Comment by axe312ger** [comment]
Neat!
