### ISSUE TITLE
Format on Save re-dirties fmted file

### ISSUE THREAD

**Issue by scottastrophic** [1000ch/atom-cssfmt#9]
The Format on Save setting is nice, but if the file is changed by said formatting, the save happens first, so you end up having to save twice.

**Comment by 1000ch** [comment]
This plugin intercepts [`onWillSave`](https://atom.io/docs/api/v0.187.0/TextBuffer#instance-onWillSave) that happen before saving, so it seems saving twice doesn't happen.
